[package]
name = "integration-maintenance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
business.workspace = true
infra-postgres.workspace = true
async-trait.workspace = true
sqlx.workspace = true
tracing.workspace = true
