[package]
name = "app-rebuild-sales"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
business.workspace = true
entry-cli.workspace = true
integration-reporting.workspace = true
infra-postgres.workspace = true
infra-telemetry.workspace = true
infra-runtime.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true

[[bin]]
name = "rebuild-sales"
path = "src/main.rs"
